In [69]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [70]:
path = "/Users/amrtamer/Documents/Internship"
# path = "/content/drive/MyDrive/Internship"

In [71]:
data = pd.read_csv(path + r'/data/Volve/Volve_cleaned.csv')
data.head()

,Unnamed: 0,date,WELL_BORE_CODE,well_name,NPD_WELL_BORE_NAME,NPD_FIELD_CODE,NPD_FIELD_NAME,NPD_FACILITY_CODE,NPD_FACILITY_NAME,prod_hrs,...,AVG_CHOKE_UOM,whp,wht,choke_size_percentage,oil_vol,gas_vol,water_vol,FLOW_KIND,well_type,oil_rate
0,0,2014-04-22,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,24.0,...,%,107.362050,37.939251,78.935409,631.47,90439.09,0.0,production,OP,631.47
1,1,2014-04-23,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,24.0,...,%,99.187011,60.756579,70.627109,1166.46,165720.39,0.0,production,OP,1166.46
2,2,2014-04-24,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,24.0,...,%,94.600770,63.046800,66.049151,1549.81,221707.31,0.0,production,OP,1549.81
3,3,2014-04-25,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,24.0,...,%,89.988092,64.547229,61.405386,1248.70,178063.52,0.0,production,OP,1248.70
4,4,2014-04-26,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,24.0,...,%,84.776810,65.723694,56.147906,1345.78,192602.19,0.0,production,OP,1345.78

In [72]:
well_info = dict(set([(j, i) for i, j in data[['WELL_BORE_CODE', 'well_name']].values.tolist()])) # creating a dictionary of well identiification with {code: name} structure
well_info

{5599: 'NO 15/9-F-12 H',
 5351: 'NO 15/9-F-14 H',
 7405: 'NO 15/9-F-1 C',
 5769: 'NO 15/9-F-5 AH',
 7289: 'NO 15/9-F-15 D',
 7078: 'NO 15/9-F-11 H'}

In [73]:
identification_column = ['well_name', 'WELL_BORE_CODE', 'date']
feature_columns = ['prod_hrs', 'bhp', 'bht', 'dp_tubing', 'AVG_ANNULUS_PRESS', 'AVG_CHOKE_SIZE_P', 'whp', 'wht', 'choke_size_percentage', 'oil_vol', 'gas_vol', 'water_vol', 'oil_rate']
target_column = ['oil_rate']

In [74]:
data = data[identification_column + feature_columns]
data.shape

(7987, 16)

In [75]:
features = data[feature_columns]
data[feature_columns] = (features - features.mean()) / features.std()
data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,wht,choke_size_percentage,oil_vol,gas_vol,water_vol,oil_rate
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029309,0.605973,0.396165,-2.015211,-0.533280,3.281836,-2.165276,3.625672,-0.464450,-0.494707,-1.131839,-0.490501
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845793,0.634777,0.239816,0.088574,-0.419656,2.849981,-0.870666,3.145767,-0.066597,-0.099321,-1.131839,-0.098101
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775023,0.639809,0.199889,-0.687843,-0.402874,2.607708,-0.740723,2.881334,0.218487,0.194728,-1.131839,0.183075
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705031,0.642083,0.161491,1.145565,-0.379061,2.364038,-0.655592,2.613101,-0.005438,-0.034494,-1.131839,-0.037781
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625355,0.643889,0.117219,1.145565,-0.340115,2.088747,-0.588842,2.309418,0.066757,0.041865,-1.131839,0.033425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814176,1.149547,1.150153,-1.140330,-1.056587,-0.926875,-0.657907,-0.665422,-1.078364,-0.681306
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814176,1.159077,1.150153,-1.136215,-1.091664,-0.922827,-0.652538,-0.659200,-1.078659,-0.676011
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814176,1.141368,1.150153,-1.137527,-1.126432,-0.924116,-0.653795,-0.661759,-1.077945,-0.677250
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327392,1.140972,1.150153,-1.140776,-1.033676,-0.927897,-0.653363,-0.658056,-1.077909,-0.676825
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434705,-0.323038,-0.323129,1.128012,0.671086,-1.123420,-1.147809,-0.909533,-0.690755,-0.695492,-1.086089,-0.673985

In [76]:
# Initialize an empty list to store predictions
data['linear_regressor'] = None
for well_name in well_info.keys():
    rolling_predictions = []
    well = data[data['well_name'] == well_name].reset_index(drop=True)
    well_index = data[data['well_name'] == well_name].index
    # Loop over each time step in the dataset
    for i in range(len(well)):
        if i > 0:
            X_train = well[feature_columns].iloc[:i]
            Y_train = well[target_column].iloc[:i]

            # Initialize and fit the linear regression model
            linear_regressor = LinearRegression()
            linear_regressor.fit(X_train, Y_train)

            # Predict the target value for the current data point
            current_features = well[feature_columns].iloc[[i]]
            prediction = linear_regressor.predict(current_features)[0]
        else:
            # If not enough data points, use a default value (e.g., the target mean or previous value)
            prediction = well[target_column].iloc[0]
        # Append the prediction to the list
        rolling_predictions.append(prediction)
    data.loc[well_index, 'linear_regressor'] = rolling_predictions
data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,wht,choke_size_percentage,oil_vol,gas_vol,water_vol,oil_rate,linear_regressor
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029309,0.605973,0.396165,-2.015211,-0.533280,3.281836,-2.165276,3.625672,-0.464450,-0.494707,-1.131839,-0.490501,-0.490501
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845793,0.634777,0.239816,0.088574,-0.419656,2.849981,-0.870666,3.145767,-0.066597,-0.099321,-1.131839,-0.098101,-0.490501
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775023,0.639809,0.199889,-0.687843,-0.402874,2.607708,-0.740723,2.881334,0.218487,0.194728,-1.131839,0.183075,-0.146593
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705031,0.642083,0.161491,1.145565,-0.379061,2.364038,-0.655592,2.613101,-0.005438,-0.034494,-1.131839,-0.037781,0.024187
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625355,0.643889,0.117219,1.145565,-0.340115,2.088747,-0.588842,2.309418,0.066757,0.041865,-1.131839,0.033425,0.057131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814176,1.149547,1.150153,-1.140330,-1.056587,-0.926875,-0.657907,-0.665422,-1.078364,-0.681306,-0.681306
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814176,1.159077,1.150153,-1.136215,-1.091664,-0.922827,-0.652538,-0.659200,-1.078659,-0.676011,-0.676011
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814176,1.141368,1.150153,-1.137527,-1.126432,-0.924116,-0.653795,-0.661759,-1.077945,-0.677250,-0.67725
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327392,1.140972,1.150153,-1.140776,-1.033676,-0.927897,-0.653363,-0.658056,-1.077909,-0.676825,-0.676825
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434705,-0.323038,-0.323129,1.128012,0.671086,-1.123420,-1.147809,-0.909533,-0.690755,-0.695492,-1.086089,-0.673985,-0.673985

In [77]:
# Compute EMA with different spans
span_short = 5
span_medium = 10
span_long = 20

# Initialize an empty list to store predictions
data['EMA_short'] = None
data['EMA_medium'] = None
data['EMA_long'] = None
for well_name in well_info.keys():
    rolling_predictions = []
    well = data[data['well_name'] == well_name].reset_index(drop=True)
    well_index = data[data['well_name'] == well_name].index
    ema_short = well[target_column].ewm(span=span_short, adjust=False).mean().values.reshape(-1)
    ema_medium = well[target_column].ewm(span=span_medium, adjust=False).mean().values.reshape(-1)
    ema_long = well[target_column].ewm(span=span_long, adjust=False).mean().values.reshape(-1)
    data.loc[well_index, 'EMA_short'] = ema_short
    data.loc[well_index, 'EMA_medium'] = ema_medium
    data.loc[well_index, 'EMA_long'] = ema_long
data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,wht,choke_size_percentage,oil_vol,gas_vol,water_vol,oil_rate,linear_regressor,EMA_short,EMA_medium,EMA_long
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029309,0.605973,0.396165,-2.015211,-0.533280,3.281836,-2.165276,3.625672,-0.464450,-0.494707,-1.131839,-0.490501,-0.490501,-0.490501,-0.490501,-0.490501
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845793,0.634777,0.239816,0.088574,-0.419656,2.849981,-0.870666,3.145767,-0.066597,-0.099321,-1.131839,-0.098101,-0.490501,-0.359701,-0.419156,-0.45313
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775023,0.639809,0.199889,-0.687843,-0.402874,2.607708,-0.740723,2.881334,0.218487,0.194728,-1.131839,0.183075,-0.146593,-0.178776,-0.309659,-0.392539
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705031,0.642083,0.161491,1.145565,-0.379061,2.364038,-0.655592,2.613101,-0.005438,-0.034494,-1.131839,-0.037781,0.024187,-0.131777,-0.260227,-0.358752
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625355,0.643889,0.117219,1.145565,-0.340115,2.088747,-0.588842,2.309418,0.066757,0.041865,-1.131839,0.033425,0.057131,-0.07671,-0.206836,-0.321402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814176,1.149547,1.150153,-1.140330,-1.056587,-0.926875,-0.657907,-0.665422,-1.078364,-0.681306,-0.681306,-0.685849,-0.691669,-0.699498
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814176,1.159077,1.150153,-1.136215,-1.091664,-0.922827,-0.652538,-0.659200,-1.078659,-0.676011,-0.676011,-0.682569,-0.688822,-0.697261
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814176,1.141368,1.150153,-1.137527,-1.126432,-0.924116,-0.653795,-0.661759,-1.077945,-0.677250,-0.67725,-0.680796,-0.686718,-0.695355
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327392,1.140972,1.150153,-1.140776,-1.033676,-0.927897,-0.653363,-0.658056,-1.077909,-0.676825,-0.676825,-0.679472,-0.684919,-0.69359
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434705,-0.323038,-0.323129,1.128012,0.671086,-1.123420,-1.147809,-0.909533,-0.690755,-0.695492,-1.086089,-0.673985,-0.673985,-0.677643,-0.682931,-0.691723

In [78]:
# Rolling window spans
window_short = 5
window_medium = 10
window_long = 20

# Initialize the rolling window columns in the DataFrame with NaN
data['Rolling_short'] = None
data['Rolling_medium'] = None
data['Rolling_long'] = None

# Iterate over each well
for well_name in data['well_name'].unique():
    # Filter the DataFrame for the current well
    well = data[data['well_name'] == well_name].reset_index(drop=True)
    well_index = data[data['well_name'] == well_name].index
    
    # Compute the rolling mean for each window
    rolling_short = well[target_column].rolling(window=window_short).mean().fillna(0).values.reshape(-1)
    rolling_medium = well[target_column].rolling(window=window_medium).mean().fillna(0).values.reshape(-1)
    rolling_long = well[target_column].rolling(window=window_long).mean().fillna(0).values.reshape(-1)

    # Store the rolling means back in the original DataFrame
    data.loc[well_index, 'Rolling_short'] = rolling_short
    data.loc[well_index, 'Rolling_medium'] = rolling_medium
    data.loc[well_index, 'Rolling_long'] = rolling_long
data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,...,gas_vol,water_vol,oil_rate,linear_regressor,EMA_short,EMA_medium,EMA_long,Rolling_short,Rolling_medium,Rolling_long
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029309,0.605973,0.396165,-2.015211,-0.533280,3.281836,...,-0.494707,-1.131839,-0.490501,-0.490501,-0.490501,-0.490501,-0.490501,0.0,0.0,0.0
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845793,0.634777,0.239816,0.088574,-0.419656,2.849981,...,-0.099321,-1.131839,-0.098101,-0.490501,-0.359701,-0.419156,-0.45313,0.0,0.0,0.0
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775023,0.639809,0.199889,-0.687843,-0.402874,2.607708,...,0.194728,-1.131839,0.183075,-0.146593,-0.178776,-0.309659,-0.392539,0.0,0.0,0.0
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705031,0.642083,0.161491,1.145565,-0.379061,2.364038,...,-0.034494,-1.131839,-0.037781,0.024187,-0.131777,-0.260227,-0.358752,0.0,0.0,0.0
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625355,0.643889,0.117219,1.145565,-0.340115,2.088747,...,0.041865,-1.131839,0.033425,0.057131,-0.07671,-0.206836,-0.321402,-0.081977,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814176,1.149547,1.150153,-1.140330,...,-0.665422,-1.078364,-0.681306,-0.681306,-0.685849,-0.691669,-0.699498,-0.685145,-0.691609,-0.705145
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814176,1.159077,1.150153,-1.136215,...,-0.659200,-1.078659,-0.676011,-0.676011,-0.682569,-0.688822,-0.697261,-0.683128,-0.688092,-0.70342
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814176,1.141368,1.150153,-1.137527,...,-0.661759,-1.077945,-0.677250,-0.67725,-0.680796,-0.686718,-0.695355,-0.681889,-0.685538,-0.701236
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327392,1.140972,1.150153,-1.140776,...,-0.658056,-1.077909,-0.676825,-0.676825,-0.679472,-0.684919,-0.69359,-0.678736,-0.683649,-0.699328
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434705,-0.323038,-0.323129,1.128012,0.671086,-1.123420,...,-0.695492,-1.086089,-0.673985,-0.673985,-0.677643,-0.682931,-0.691723,-0.677075,-0.682138,-0.696975

In [79]:
short_lag = 3
medium_lag = 5
long_lag = 10

data['Lag_short'] = None
data['Lag_medium'] = None
data['Lag_long'] = None

# Iterate over each well
for well_name in well_info.keys():
    # Filter the DataFrame for the current well
    well = data[data['well_name'] == well_name].reset_index(drop=True)
    well_index = data[data['well_name'] == well_name].index
    for lag, name in zip([short_lag, medium_lag, long_lag], ['Lag_short', 'Lag_medium', 'Lag_long']):
        lags = []
        # Create lagged values with padding for the initial values
        start_shift = well[target_column].shift(lag).fillna(0).values.reshape(-1)
        for i in range(0, lag): 
            lags.append(list(start_shift[i:i+lag]))

        # Create lagged values for the remaining rows
        for i in range(lag-1, len(well) - 1): 
            lags.append(list(well.loc[i-lag+1:i, target_column].values.reshape(-1)))

        # Assign the lagged list to the DataFrame
        for i, j in enumerate(list(well_index)):
            data.at[j, name] = lags[i]

data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,...,linear_regressor,EMA_short,EMA_medium,EMA_long,Rolling_short,Rolling_medium,Rolling_long,Lag_short,Lag_medium,Lag_long
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029309,0.605973,0.396165,-2.015211,-0.533280,3.281836,...,-0.490501,-0.490501,-0.490501,-0.490501,0.0,0.0,0.0,"[0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845793,0.634777,0.239816,0.088574,-0.419656,2.849981,...,-0.490501,-0.359701,-0.419156,-0.45313,0.0,0.0,0.0,"[0.0, 0.0, -0.4905010756171413]","[0.0, 0.0, 0.0, 0.0, -0.4905010756171413]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775023,0.639809,0.199889,-0.687843,-0.402874,2.607708,...,-0.146593,-0.178776,-0.309659,-0.392539,0.0,0.0,0.0,"[0.0, -0.4905010756171413, -0.09810136648612545]","[0.0, 0.0, 0.0, -0.4905010756171413, -0.098101...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.49..."
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705031,0.642083,0.161491,1.145565,-0.379061,2.364038,...,0.024187,-0.131777,-0.260227,-0.358752,0.0,0.0,0.0,"[-0.4905010756171413, -0.09810136648612545, 0....","[0.0, 0.0, -0.4905010756171413, -0.09810136648...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.4905010..."
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625355,0.643889,0.117219,1.145565,-0.340115,2.088747,...,0.057131,-0.07671,-0.206836,-0.321402,-0.081977,0.0,0.0,"[-0.09810136648612545, 0.18307478352672518, -0...","[0.0, -0.4905010756171413, -0.0981013664861254...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.490501075617..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814176,1.149547,1.150153,-1.140330,...,-0.681306,-0.685849,-0.691669,-0.699498,-0.685145,-0.691609,-0.705145,"[-0.6834479858098645, -0.6925870358402809, -0....","[-0.6915821804196012, -0.6860958165169114, -0....","[-0.7117159623886966, -0.7111878631895072, -0...."
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814176,1.159077,1.150153,-1.136215,...,-0.676011,-0.682569,-0.688822,-0.697261,-0.683128,-0.688092,-0.70342,"[-0.6925870358402809, -0.6822891014560878, -0....","[-0.6860958165169114, -0.6834479858098645, -0....","[-0.7111878631895072, -0.7027822842690761, -0...."
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814176,1.141368,1.150153,-1.137527,...,-0.67725,-0.680796,-0.686718,-0.695355,-0.681889,-0.685538,-0.701236,"[-0.6822891014560878, -0.6813062501687076, -0....","[-0.6834479858098645, -0.6925870358402809, -0....","[-0.7027822842690761, -0.695718957479918, -0.6..."
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327392,1.140972,1.150153,-1.140776,...,-0.676825,-0.679472,-0.684919,-0.69359,-0.678736,-0.683649,-0.699328,"[-0.6813062501687076, -0.6760105887546141, -0....","[-0.6925870358402809, -0.6822891014560878, -0....","[-0.695718957479918, -0.689095713356751, -0.69..."
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434705,-0.323038,-0.323129,1.128012,0.671086,-1.123420,...,-0.673985,-0.677643,-0.682931,-0.691723,-0.677075,-0.682138,-0.696975,"[-0.6760105887546141, -0.6772501549304891, -0....","[-0.6822891014560878, -0.6813062501687076, -0....","[-0.689095713356751, -0.6915821804196012, -0.6..."

In [80]:
new_feature_columns = ['linear_regressor',	'EMA_short', 'EMA_medium', 'EMA_long', 'Rolling_short',	'Rolling_medium', 'Rolling_long']
new_features = data[new_feature_columns]
data[new_feature_columns] = (new_features - new_features.mean()) / new_features.std()
data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,...,linear_regressor,EMA_short,EMA_medium,EMA_long,Rolling_short,Rolling_medium,Rolling_long,Lag_short,Lag_medium,Lag_long
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029309,0.605973,0.396165,-2.015211,-0.533280,3.281836,...,-0.489929,-0.495877,-0.498713,-0.502834,-0.001433,-0.0027,-0.005271,"[0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845793,0.634777,0.239816,0.088574,-0.419656,2.849981,...,-0.489929,-0.363747,-0.426301,-0.464667,-0.001433,-0.0027,-0.005271,"[0.0, 0.0, -0.4905010756171413]","[0.0, 0.0, 0.0, 0.0, -0.4905010756171413]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775023,0.639809,0.199889,-0.687843,-0.402874,2.607708,...,-0.146007,-0.180982,-0.315168,-0.402787,-0.001433,-0.0027,-0.005271,"[0.0, -0.4905010756171413, -0.09810136648612545]","[0.0, 0.0, 0.0, -0.4905010756171413, -0.098101...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.49..."
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705031,0.642083,0.161491,1.145565,-0.379061,2.364038,...,0.024781,-0.133505,-0.264997,-0.368282,-0.001433,-0.0027,-0.005271,"[-0.4905010756171413, -0.09810136648612545, 0....","[0.0, 0.0, -0.4905010756171413, -0.09810136648...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.4905010..."
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625355,0.643889,0.117219,1.145565,-0.340115,2.088747,...,0.057726,-0.077878,-0.210807,-0.330137,-0.084172,-0.0027,-0.005271,"[-0.09810136648612545, 0.18307478352672518, -0...","[0.0, -0.4905010756171413, -0.0981013664861254...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.490501075617..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814176,1.149547,1.150153,-1.140330,...,-0.680743,-0.693212,-0.702888,-0.716277,-0.692951,-0.704178,-0.725482,"[-0.6834479858098645, -0.6925870358402809, -0....","[-0.6915821804196012, -0.6860958165169114, -0....","[-0.7117159623886966, -0.7111878631895072, -0...."
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814176,1.159077,1.150153,-1.136215,...,-0.675447,-0.689899,-0.699999,-0.713993,-0.690916,-0.70061,-0.723721,"[-0.6925870358402809, -0.6822891014560878, -0....","[-0.6860958165169114, -0.6834479858098645, -0....","[-0.7111878631895072, -0.7027822842690761, -0...."
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814176,1.141368,1.150153,-1.137527,...,-0.676686,-0.688108,-0.697863,-0.712046,-0.689665,-0.69802,-0.72149,"[-0.6822891014560878, -0.6813062501687076, -0....","[-0.6834479858098645, -0.6925870358402809, -0....","[-0.7027822842690761, -0.695718957479918, -0.6..."
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327392,1.140972,1.150153,-1.140776,...,-0.676261,-0.686771,-0.696038,-0.710244,-0.686483,-0.696104,-0.719541,"[-0.6813062501687076, -0.6760105887546141, -0....","[-0.6925870358402809, -0.6822891014560878, -0....","[-0.695718957479918, -0.689095713356751, -0.69..."
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434705,-0.323038,-0.323129,1.128012,0.671086,-1.123420,...,-0.673421,-0.684923,-0.69402,-0.708337,-0.684807,-0.694571,-0.717138,"[-0.6760105887546141, -0.6772501549304891, -0....","[-0.6822891014560878, -0.6813062501687076, -0....","[-0.689095713356751, -0.6915821804196012, -0.6..."

In [81]:
print(data[['prod_hrs', 'bhp', 'bht', 'dp_tubing', 'AVG_ANNULUS_PRESS', 'AVG_CHOKE_SIZE_P', 'whp', 'wht', 'choke_size_percentage', 'oil_vol', 'gas_vol', 'water_vol', 'linear_regressor', 'EMA_short', 'EMA_medium', 'EMA_long', 'Rolling_short', 'Rolling_medium', 'Rolling_long', 'oil_rate']].mean().round(10))
print(data[['prod_hrs', 'bhp', 'bht', 'dp_tubing', 'AVG_ANNULUS_PRESS', 'AVG_CHOKE_SIZE_P', 'whp', 'wht', 'choke_size_percentage', 'oil_vol', 'gas_vol', 'water_vol', 'linear_regressor', 'EMA_short', 'EMA_medium', 'EMA_long', 'Rolling_short', 'Rolling_medium', 'Rolling_long', 'oil_rate']].std().round(10))

prod_hrs                -0.0
bhp                      0.0
bht                     -0.0
dp_tubing                0.0
AVG_ANNULUS_PRESS        0.0
AVG_CHOKE_SIZE_P        -0.0
whp                     -0.0
wht                     -0.0
choke_size_percentage    0.0
oil_vol                  0.0
gas_vol                 -0.0
water_vol                0.0
linear_regressor         0.0
EMA_short                0.0
EMA_medium              -0.0
EMA_long                 0.0
Rolling_short            0.0
Rolling_medium           0.0
Rolling_long            -0.0
oil_rate                -0.0
dtype: float64
prod_hrs                 1.0
bhp                      1.0
bht                      1.0
dp_tubing                1.0
AVG_ANNULUS_PRESS        1.0
AVG_CHOKE_SIZE_P         1.0
whp                      1.0
wht                      1.0
choke_size_percentage    1.0
oil_vol                  1.0
gas_vol                  1.0
water_vol                1.0
linear_regressor         1.0
EMA_short                1.0
EMA_medium               1.0
EMA_long                 1.0
Rolling_short            1.0
Rolling_medium           1.0
Rolling_long             1.0
oil_rate                 1.0
dtype: float64

In [82]:
data.to_pickle(path + "/data/Volve/Volve_cleaned_prepared.pkl")
data.to_csv(path + "/data/Volve/Volve_cleaned_prepared.csv")

In [83]:
data = pd.read_pickle(path + r'/data/Volve/Volve_cleaned_prepared.pkl')
data.head()

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,...,linear_regressor,EMA_short,EMA_medium,EMA_long,Rolling_short,Rolling_medium,Rolling_long,Lag_short,Lag_medium,Lag_long
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029309,0.605973,0.396165,-2.015211,-0.533280,3.281836,...,-0.489929,-0.495877,-0.498713,-0.502834,-0.001433,-0.0027,-0.005271,"[0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845793,0.634777,0.239816,0.088574,-0.419656,2.849981,...,-0.489929,-0.363747,-0.426301,-0.464667,-0.001433,-0.0027,-0.005271,"[0.0, 0.0, -0.4905010756171413]","[0.0, 0.0, 0.0, 0.0, -0.4905010756171413]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775023,0.639809,0.199889,-0.687843,-0.402874,2.607708,...,-0.146007,-0.180982,-0.315168,-0.402787,-0.001433,-0.0027,-0.005271,"[0.0, -0.4905010756171413, -0.09810136648612545]","[0.0, 0.0, 0.0, -0.4905010756171413, -0.098101...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.49..."
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705031,0.642083,0.161491,1.145565,-0.379061,2.364038,...,0.024781,-0.133505,-0.264997,-0.368282,-0.001433,-0.0027,-0.005271,"[-0.4905010756171413, -0.09810136648612545, 0....","[0.0, 0.0, -0.4905010756171413, -0.09810136648...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.4905010..."
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625355,0.643889,0.117219,1.145565,-0.340115,2.088747,...,0.057726,-0.077878,-0.210807,-0.330137,-0.084172,-0.0027,-0.005271,"[-0.09810136648612545, 0.18307478352672518, -0...","[0.0, -0.4905010756171413, -0.0981013664861254...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.490501075617..."

In [84]:
data_expanded = data.copy()
for column in ['Lag_short', 'Lag_medium', 'Lag_long']:
    # Expand the 'lists' column into separate columns
    expanded_lists = pd.DataFrame(data[column].tolist(), columns=[column+f"_{i}" for i in range(len(data.loc[0, column]))], index=data.index)
    # Join the expanded columns back to the original DataFrame
    data_expanded = data_expanded.join(expanded_lists)
    # Optionally, drop the original list columns
    data_expanded.drop(columns=column, inplace=True)

data_expanded

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,...,Lag_long_0,Lag_long_1,Lag_long_2,Lag_long_3,Lag_long_4,Lag_long_5,Lag_long_6,Lag_long_7,Lag_long_8,Lag_long_9
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029309,0.605973,0.396165,-2.015211,-0.533280,3.281836,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845793,0.634777,0.239816,0.088574,-0.419656,2.849981,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.490501
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775023,0.639809,0.199889,-0.687843,-0.402874,2.607708,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.490501,-0.098101
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705031,0.642083,0.161491,1.145565,-0.379061,2.364038,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.490501,-0.098101,0.183075
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625355,0.643889,0.117219,1.145565,-0.340115,2.088747,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.490501,-0.098101,0.183075,-0.037781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814176,1.149547,1.150153,-1.140330,...,-0.711716,-0.711188,-0.702782,-0.695719,-0.689096,-0.691582,-0.686096,-0.683448,-0.692587,-0.682289
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814176,1.159077,1.150153,-1.136215,...,-0.711188,-0.702782,-0.695719,-0.689096,-0.691582,-0.686096,-0.683448,-0.692587,-0.682289,-0.681306
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814176,1.141368,1.150153,-1.137527,...,-0.702782,-0.695719,-0.689096,-0.691582,-0.686096,-0.683448,-0.692587,-0.682289,-0.681306,-0.676011
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327392,1.140972,1.150153,-1.140776,...,-0.695719,-0.689096,-0.691582,-0.686096,-0.683448,-0.692587,-0.682289,-0.681306,-0.676011,-0.677250
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434705,-0.323038,-0.323129,1.128012,0.671086,-1.123420,...,-0.689096,-0.691582,-0.686096,-0.683448,-0.692587,-0.682289,-0.681306,-0.676011,-0.677250,-0.676825

In [85]:
data_expanded.to_pickle(path + "/data/Volve/Volve_cleaned_prepared_flattened.pkl")

In [86]:
train_size = 0.6
val_size = 0.2
test_size = 0.2

In [87]:
train_wells = []
test_wells = []
for i in well_info.keys():
    well = data_expanded[data_expanded['well_name'] == i]
    train_set_length = int((train_size + val_size) * len(well))
    train_wells.append(well[:train_set_length + 1])
    test_set_length = int(test_size * len(well))
    test_wells.append(well[-test_set_length:])

# Flatten the lists of DataFrames
temp_data = pd.concat(train_wells).reset_index(drop=True)
data_test = pd.concat(test_wells).reset_index(drop=True)

data_test.reset_index(drop=True, inplace=True)

data_test.to_pickle(path + "/data/Volve/data_test_flattened.pkl")