In [33]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [17]:
path = "/Users/amrtamer/Documents/Internship"
# path = "/content/drive/MyDrive/Internship"

In [18]:
data = pd.read_csv(path + r'/data/Volve/Volve_cleaned.csv')
data.head()

,Unnamed: 0,date,WELL_BORE_CODE,well_name,NPD_WELL_BORE_NAME,NPD_FIELD_CODE,NPD_FIELD_NAME,NPD_FACILITY_CODE,NPD_FACILITY_NAME,prod_hrs,...,AVG_CHOKE_UOM,whp,wht,choke_size_percentage,oil_vol,gas_vol,water_vol,FLOW_KIND,well_type,oil_rate
0,0,2014-04-22,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,24.0,...,%,107.362050,37.939251,78.935409,631.47,90439.09,0.0,production,OP,1166.46
1,1,2014-04-23,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,24.0,...,%,99.187011,60.756579,70.627109,1166.46,165720.39,0.0,production,OP,1166.46
2,2,2014-04-24,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,24.0,...,%,94.600770,63.046800,66.049151,1549.81,221707.31,0.0,production,OP,1549.81
3,3,2014-04-25,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,24.0,...,%,89.988092,64.547229,61.405386,1248.70,178063.52,0.0,production,OP,1248.70
4,4,2014-04-26,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,24.0,...,%,84.776810,65.723694,56.147906,1345.78,192602.19,0.0,production,OP,1345.78

In [19]:
well_info = dict(set([(j, i) for i, j in data[['WELL_BORE_CODE', 'well_name']].values.tolist()])) # creating a dictionary of well identiification with {code: name} structure
well_info

{7405: 'NO 15/9-F-1 C',
 7289: 'NO 15/9-F-15 D',
 5599: 'NO 15/9-F-12 H',
 7078: 'NO 15/9-F-11 H',
 5769: 'NO 15/9-F-5 AH',
 5351: 'NO 15/9-F-14 H'}

In [20]:
identification_column = ['well_name', 'WELL_BORE_CODE', 'date']
feature_columns = ['prod_hrs', 'bhp', 'bht', 'dp_tubing', 'AVG_ANNULUS_PRESS', 'AVG_CHOKE_SIZE_P', 'whp', 'wht', 'choke_size_percentage', 'oil_vol', 'gas_vol', 'water_vol', 'oil_rate']
target_column = ['oil_rate']

In [21]:
data = data[identification_column + feature_columns]
data.shape

(7987, 16)

In [22]:
features = data[feature_columns]
data[feature_columns] = (features - features.mean()) / features.std()
data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,wht,choke_size_percentage,oil_vol,gas_vol,water_vol,oil_rate
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029311,0.605973,0.396167,-2.016027,-0.533280,3.281836,-2.165276,3.625672,-0.464450,-0.494707,-1.131839,-0.102310
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845795,0.634777,0.239818,0.088113,-0.419656,2.849981,-0.870666,3.145767,-0.066597,-0.099321,-1.131839,-0.102310
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775025,0.639809,0.199890,-0.688434,-0.402874,2.607708,-0.740723,2.881334,0.218487,0.194728,-1.131839,0.177706
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705033,0.642084,0.161493,1.145283,-0.379061,2.364038,-0.655592,2.613101,-0.005438,-0.034494,-1.131839,-0.042238
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625357,0.643889,0.117221,1.145283,-0.340115,2.088747,-0.588842,2.309418,0.066757,0.041865,-1.131839,0.028674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814175,1.149266,1.150153,-1.140330,-1.056587,-0.926875,-0.657907,-0.665422,-1.078364,-0.683109
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814175,1.158798,1.150153,-1.136215,-1.091664,-0.922827,-0.652538,-0.659200,-1.078659,-0.677835
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814175,1.141085,1.150153,-1.137527,-1.126432,-0.924116,-0.653795,-0.661759,-1.077945,-0.679069
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327391,1.140689,1.150153,-1.140776,-1.033676,-0.927897,-0.653363,-0.658056,-1.077909,-0.678646
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434704,-0.323038,-0.323127,1.127728,0.671086,-1.123420,-1.147809,-0.909533,-0.690755,-0.695492,-1.086089,-0.675818

In [23]:
# Initialize an empty list to store predictions
data['linear_regressor'] = None
for well_name in well_info.keys():
    rolling_predictions = []
    well = data[data['well_name'] == well_name].reset_index(drop=True)
    well_index = data[data['well_name'] == well_name].index
    # Loop over each time step in the dataset
    for i in range(len(well)):
        if i > 0:
            X_train = well[feature_columns].iloc[:i]
            Y_train = well[target_column].iloc[:i]

            # Initialize and fit the linear regression model
            linear_regressor = LinearRegression()
            linear_regressor.fit(X_train, Y_train)

            # Predict the target value for the current data point
            current_features = well[feature_columns].iloc[[i]]
            prediction = linear_regressor.predict(current_features)[0]
        else:
            # If not enough data points, use a default value (e.g., the target mean or previous value)
            prediction = well[target_column].iloc[0]
        # Append the prediction to the list
        rolling_predictions.append(prediction)
    data.loc[well_index, 'linear_regressor'] = rolling_predictions
data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,wht,choke_size_percentage,oil_vol,gas_vol,water_vol,oil_rate,linear_regressor
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029311,0.605973,0.396167,-2.016027,-0.533280,3.281836,-2.165276,3.625672,-0.464450,-0.494707,-1.131839,-0.102310,-0.10231
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845795,0.634777,0.239818,0.088113,-0.419656,2.849981,-0.870666,3.145767,-0.066597,-0.099321,-1.131839,-0.102310,-0.10231
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775025,0.639809,0.199890,-0.688434,-0.402874,2.607708,-0.740723,2.881334,0.218487,0.194728,-1.131839,0.177706,-0.10231
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705033,0.642084,0.161493,1.145283,-0.379061,2.364038,-0.655592,2.613101,-0.005438,-0.034494,-1.131839,-0.042238,-0.115175
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625357,0.643889,0.117221,1.145283,-0.340115,2.088747,-0.588842,2.309418,0.066757,0.041865,-1.131839,0.028674,0.08185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814175,1.149266,1.150153,-1.140330,-1.056587,-0.926875,-0.657907,-0.665422,-1.078364,-0.683109,-0.683109
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814175,1.158798,1.150153,-1.136215,-1.091664,-0.922827,-0.652538,-0.659200,-1.078659,-0.677835,-0.677835
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814175,1.141085,1.150153,-1.137527,-1.126432,-0.924116,-0.653795,-0.661759,-1.077945,-0.679069,-0.679069
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327391,1.140689,1.150153,-1.140776,-1.033676,-0.927897,-0.653363,-0.658056,-1.077909,-0.678646,-0.678646
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434704,-0.323038,-0.323127,1.127728,0.671086,-1.123420,-1.147809,-0.909533,-0.690755,-0.695492,-1.086089,-0.675818,-0.675818

In [24]:
# Compute EMA with different spans
span_short = 5
span_medium = 10
span_long = 20

# Initialize an empty list to store predictions
data['EMA_short'] = None
data['EMA_medium'] = None
data['EMA_long'] = None
for well_name in well_info.keys():
    rolling_predictions = []
    well = data[data['well_name'] == well_name].reset_index(drop=True)
    well_index = data[data['well_name'] == well_name].index
    ema_short = well[target_column].ewm(span=span_short, adjust=False).mean().values.reshape(-1)
    ema_medium = well[target_column].ewm(span=span_medium, adjust=False).mean().values.reshape(-1)
    ema_long = well[target_column].ewm(span=span_long, adjust=False).mean().values.reshape(-1)
    data.loc[well_index, 'EMA_short'] = ema_short
    data.loc[well_index, 'EMA_medium'] = ema_medium
    data.loc[well_index, 'EMA_long'] = ema_long
data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,wht,choke_size_percentage,oil_vol,gas_vol,water_vol,oil_rate,linear_regressor,EMA_short,EMA_medium,EMA_long
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029311,0.605973,0.396167,-2.016027,-0.533280,3.281836,-2.165276,3.625672,-0.464450,-0.494707,-1.131839,-0.102310,-0.10231,-0.10231,-0.10231,-0.10231
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845795,0.634777,0.239818,0.088113,-0.419656,2.849981,-0.870666,3.145767,-0.066597,-0.099321,-1.131839,-0.102310,-0.10231,-0.10231,-0.10231,-0.10231
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775025,0.639809,0.199890,-0.688434,-0.402874,2.607708,-0.740723,2.881334,0.218487,0.194728,-1.131839,0.177706,-0.10231,-0.008971,-0.051398,-0.075642
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705033,0.642084,0.161493,1.145283,-0.379061,2.364038,-0.655592,2.613101,-0.005438,-0.034494,-1.131839,-0.042238,-0.115175,-0.02006,-0.049732,-0.07246
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625357,0.643889,0.117221,1.145283,-0.340115,2.088747,-0.588842,2.309418,0.066757,0.041865,-1.131839,0.028674,0.08185,-0.003815,-0.035477,-0.062828
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814175,1.149266,1.150153,-1.140330,-1.056587,-0.926875,-0.657907,-0.665422,-1.078364,-0.683109,-0.683109,-0.687632,-0.693351,-0.700317
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814175,1.158798,1.150153,-1.136215,-1.091664,-0.922827,-0.652538,-0.659200,-1.078659,-0.677835,-0.677835,-0.684366,-0.69053,-0.698176
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814175,1.141085,1.150153,-1.137527,-1.126432,-0.924116,-0.653795,-0.661759,-1.077945,-0.679069,-0.679069,-0.682601,-0.688446,-0.696356
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327391,1.140689,1.150153,-1.140776,-1.033676,-0.927897,-0.653363,-0.658056,-1.077909,-0.678646,-0.678646,-0.681282,-0.686664,-0.69467
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434704,-0.323038,-0.323127,1.127728,0.671086,-1.123420,-1.147809,-0.909533,-0.690755,-0.695492,-1.086089,-0.675818,-0.675818,-0.679461,-0.684692,-0.692874

In [25]:
# Rolling window spans
window_short = 5
window_medium = 10
window_long = 20

# Initialize the rolling window columns in the DataFrame with NaN
data['Rolling_short'] = None
data['Rolling_medium'] = None
data['Rolling_long'] = None

# Iterate over each well
for well_name in data['well_name'].unique():
    # Filter the DataFrame for the current well
    well = data[data['well_name'] == well_name].reset_index(drop=True)
    well_index = data[data['well_name'] == well_name].index
    
    # Compute the rolling mean for each window
    rolling_short = well[target_column].rolling(window=window_short).mean().fillna(0).values.reshape(-1)
    rolling_medium = well[target_column].rolling(window=window_medium).mean().fillna(0).values.reshape(-1)
    rolling_long = well[target_column].rolling(window=window_long).mean().fillna(0).values.reshape(-1)

    # Store the rolling means back in the original DataFrame
    data.loc[well_index, 'Rolling_short'] = rolling_short
    data.loc[well_index, 'Rolling_medium'] = rolling_medium
    data.loc[well_index, 'Rolling_long'] = rolling_long
data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,...,gas_vol,water_vol,oil_rate,linear_regressor,EMA_short,EMA_medium,EMA_long,Rolling_short,Rolling_medium,Rolling_long
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029311,0.605973,0.396167,-2.016027,-0.533280,3.281836,...,-0.494707,-1.131839,-0.102310,-0.10231,-0.10231,-0.10231,-0.10231,0.0,0.0,0.0
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845795,0.634777,0.239818,0.088113,-0.419656,2.849981,...,-0.099321,-1.131839,-0.102310,-0.10231,-0.10231,-0.10231,-0.10231,0.0,0.0,0.0
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775025,0.639809,0.199890,-0.688434,-0.402874,2.607708,...,0.194728,-1.131839,0.177706,-0.10231,-0.008971,-0.051398,-0.075642,0.0,0.0,0.0
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705033,0.642084,0.161493,1.145283,-0.379061,2.364038,...,-0.034494,-1.131839,-0.042238,-0.115175,-0.02006,-0.049732,-0.07246,0.0,0.0,0.0
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625357,0.643889,0.117221,1.145283,-0.340115,2.088747,...,0.041865,-1.131839,0.028674,0.08185,-0.003815,-0.035477,-0.062828,-0.008096,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814175,1.149266,1.150153,-1.140330,...,-0.665422,-1.078364,-0.683109,-0.683109,-0.687632,-0.693351,-0.700317,-0.686932,-0.693369,-0.706849
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814175,1.158798,1.150153,-1.136215,...,-0.659200,-1.078659,-0.677835,-0.677835,-0.684366,-0.69053,-0.698176,-0.684923,-0.689866,-0.705131
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814175,1.141085,1.150153,-1.137527,...,-0.661759,-1.077945,-0.679069,-0.679069,-0.682601,-0.688446,-0.696356,-0.683689,-0.687323,-0.702956
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327391,1.140689,1.150153,-1.140776,...,-0.658056,-1.077909,-0.678646,-0.678646,-0.681282,-0.686664,-0.69467,-0.680549,-0.685442,-0.701056
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434704,-0.323038,-0.323127,1.127728,0.671086,-1.123420,...,-0.695492,-1.086089,-0.675818,-0.675818,-0.679461,-0.684692,-0.692874,-0.678895,-0.683937,-0.698713

In [26]:
short_lag = 3
medium_lag = 5
long_lag = 10

data['Lag_short'] = None
data['Lag_medium'] = None
data['Lag_long'] = None

# Iterate over each well
for well_name in well_info.keys():
    # Filter the DataFrame for the current well
    well = data[data['well_name'] == well_name].reset_index(drop=True)
    well_index = data[data['well_name'] == well_name].index
    for lag, name in zip([short_lag, medium_lag, long_lag], ['Lag_short', 'Lag_medium', 'Lag_long']):
        lags = []
        # Create lagged values with padding for the initial values
        start_shift = well[target_column].shift(lag).fillna(0).values.reshape(-1)
        for i in range(0, lag): 
            lags.append(list(start_shift[i:i+lag]))

        # Create lagged values for the remaining rows
        for i in range(lag-1, len(well) - 1): 
            lags.append(list(well.loc[i-lag+1:i, target_column].values.reshape(-1)))

        # Assign the lagged list to the DataFrame
        for i, j in enumerate(list(well_index)):
            data.at[j, name] = lags[i]

data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,...,linear_regressor,EMA_short,EMA_medium,EMA_long,Rolling_short,Rolling_medium,Rolling_long,Lag_short,Lag_medium,Lag_long
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029311,0.605973,0.396167,-2.016027,-0.533280,3.281836,...,-0.10231,-0.10231,-0.10231,-0.10231,0.0,0.0,0.0,"[0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845795,0.634777,0.239818,0.088113,-0.419656,2.849981,...,-0.10231,-0.10231,-0.10231,-0.10231,0.0,0.0,0.0,"[0.0, 0.0, -0.10230979661544379]","[0.0, 0.0, 0.0, 0.0, -0.10230979661544379]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775025,0.639809,0.199890,-0.688434,-0.402874,2.607708,...,-0.10231,-0.008971,-0.051398,-0.075642,0.0,0.0,0.0,"[0.0, -0.10230979661544379, -0.10230979661544379]","[0.0, 0.0, 0.0, -0.10230979661544379, -0.10230...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.10..."
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705033,0.642084,0.161493,1.145283,-0.379061,2.364038,...,-0.115175,-0.02006,-0.049732,-0.07246,0.0,0.0,0.0,"[-0.10230979661544379, -0.10230979661544379, 0...","[0.0, 0.0, -0.10230979661544379, -0.1023097966...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.1023097..."
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625357,0.643889,0.117221,1.145283,-0.340115,2.088747,...,0.08185,-0.003815,-0.035477,-0.062828,-0.008096,0.0,0.0,"[-0.10230979661544379, 0.1777063666263608, -0....","[0.0, -0.10230979661544379, -0.102309796615443...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.102309796615..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814175,1.149266,1.150153,-1.140330,...,-0.683109,-0.687632,-0.693351,-0.700317,-0.686932,-0.693369,-0.706849,"[-0.6852415797773639, -0.6943429268335604, -0....","[-0.6933422169244923, -0.687878486910018, -0.6...","[-0.7133929373653101, -0.7128670168291575, -0...."
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814175,1.158798,1.150153,-1.136215,...,-0.677835,-0.684366,-0.69053,-0.698176,-0.684923,-0.689866,-0.705131,"[-0.6943429268335604, -0.6840874763785847, -0....","[-0.687878486910018, -0.6852415797773639, -0.6...","[-0.7128670168291575, -0.704496114962062, -0.6..."
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814175,1.141085,1.150153,-1.137527,...,-0.679069,-0.682601,-0.688446,-0.696356,-0.683689,-0.687323,-0.702956,"[-0.6840874763785847, -0.6831086798251896, -0....","[-0.6852415797773639, -0.6943429268335604, -0....","[-0.704496114962062, -0.6974619277910209, -0.6..."
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327391,1.140689,1.150153,-1.140776,...,-0.678646,-0.681282,-0.686664,-0.69467,-0.680549,-0.685442,-0.701056,"[-0.6831086798251896, -0.6778348655598816, -0....","[-0.6943429268335604, -0.6840874763785847, -0....","[-0.6974619277910209, -0.6908660077334403, -0...."
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434704,-0.323038,-0.323127,1.127728,0.671086,-1.123420,...,-0.675818,-0.679461,-0.684692,-0.692874,-0.678895,-0.683937,-0.698713,"[-0.6778348655598816, -0.6790693179294619, -0....","[-0.6840874763785847, -0.6831086798251896, -0....","[-0.6908660077334403, -0.6933422169244923, -0...."

In [27]:
new_feature_columns = ['linear_regressor',	'EMA_short', 'EMA_medium', 'EMA_long', 'Rolling_short',	'Rolling_medium', 'Rolling_long']
new_features = data[new_feature_columns]
data[new_feature_columns] = (new_features - new_features.mean()) / new_features.std()
data

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,...,linear_regressor,EMA_short,EMA_medium,EMA_long,Rolling_short,Rolling_medium,Rolling_long,Lag_short,Lag_medium,Lag_long
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029311,0.605973,0.396167,-2.016027,-0.533280,3.281836,...,-0.101892,-0.103579,-0.104768,-0.106929,-0.001355,-0.002618,-0.00519,"[0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845795,0.634777,0.239818,0.088113,-0.419656,2.849981,...,-0.101892,-0.103579,-0.104768,-0.106929,-0.001355,-0.002618,-0.00519,"[0.0, 0.0, -0.10230979661544379]","[0.0, 0.0, 0.0, 0.0, -0.10230979661544379]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775025,0.639809,0.199890,-0.688434,-0.402874,2.607708,...,-0.101892,-0.009618,-0.053295,-0.079801,-0.001355,-0.002618,-0.00519,"[0.0, -0.10230979661544379, -0.10230979661544379]","[0.0, 0.0, 0.0, -0.10230979661544379, -0.10230...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.10..."
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705033,0.642084,0.161493,1.145283,-0.379061,2.364038,...,-0.114759,-0.020781,-0.051611,-0.076565,-0.001355,-0.002618,-0.00519,"[-0.10230979661544379, -0.10230979661544379, 0...","[0.0, 0.0, -0.10230979661544379, -0.1023097966...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.1023097..."
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625357,0.643889,0.117221,1.145283,-0.340115,2.088747,...,0.082297,-0.004428,-0.037199,-0.066767,-0.009496,-0.002618,-0.00519,"[-0.10230979661544379, 0.1777063666263608, -0....","[0.0, -0.10230979661544379, -0.102309796615443...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.102309796615..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814175,1.149266,1.150153,-1.140330,...,-0.682782,-0.692802,-0.702316,-0.715245,-0.692202,-0.703021,-0.724022,"[-0.6852415797773639, -0.6943429268335604, -0....","[-0.6933422169244923, -0.687878486910018, -0.6...","[-0.7133929373653101, -0.7128670168291575, -0...."
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814175,1.158798,1.150153,-1.136215,...,-0.677508,-0.689514,-0.699464,-0.713067,-0.690182,-0.699482,-0.722275,"[-0.6943429268335604, -0.6840874763785847, -0....","[-0.687878486910018, -0.6852415797773639, -0.6...","[-0.7128670168291575, -0.704496114962062, -0.6..."
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814175,1.141085,1.150153,-1.137527,...,-0.678742,-0.687737,-0.697357,-0.711216,-0.68894,-0.696914,-0.720063,"[-0.6840874763785847, -0.6831086798251896, -0....","[-0.6852415797773639, -0.6943429268335604, -0....","[-0.704496114962062, -0.6974619277910209, -0.6..."
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327391,1.140689,1.150153,-1.140776,...,-0.678319,-0.68641,-0.695555,-0.7095,-0.685783,-0.695013,-0.71813,"[-0.6831086798251896, -0.6778348655598816, -0....","[-0.6943429268335604, -0.6840874763785847, -0....","[-0.6974619277910209, -0.6908660077334403, -0...."
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434704,-0.323038,-0.323127,1.127728,0.671086,-1.123420,...,-0.67549,-0.684576,-0.693562,-0.707674,-0.684119,-0.693493,-0.715748,"[-0.6778348655598816, -0.6790693179294619, -0....","[-0.6840874763785847, -0.6831086798251896, -0....","[-0.6908660077334403, -0.6933422169244923, -0...."

In [28]:
print(data[['prod_hrs', 'bhp', 'bht', 'dp_tubing', 'AVG_ANNULUS_PRESS', 'AVG_CHOKE_SIZE_P', 'whp', 'wht', 'choke_size_percentage', 'oil_vol', 'gas_vol', 'water_vol', 'linear_regressor', 'EMA_short', 'EMA_medium', 'EMA_long', 'Rolling_short', 'Rolling_medium', 'Rolling_long', 'oil_rate']].mean().round(10))
print(data[['prod_hrs', 'bhp', 'bht', 'dp_tubing', 'AVG_ANNULUS_PRESS', 'AVG_CHOKE_SIZE_P', 'whp', 'wht', 'choke_size_percentage', 'oil_vol', 'gas_vol', 'water_vol', 'linear_regressor', 'EMA_short', 'EMA_medium', 'EMA_long', 'Rolling_short', 'Rolling_medium', 'Rolling_long', 'oil_rate']].std().round(10))

prod_hrs                -0.0
bhp                     -0.0
bht                      0.0
dp_tubing               -0.0
AVG_ANNULUS_PRESS       -0.0
AVG_CHOKE_SIZE_P        -0.0
whp                     -0.0
wht                     -0.0
choke_size_percentage    0.0
oil_vol                  0.0
gas_vol                 -0.0
water_vol                0.0
linear_regressor        -0.0
EMA_short                0.0
EMA_medium               0.0
EMA_long                -0.0
Rolling_short           -0.0
Rolling_medium           0.0
Rolling_long             0.0
oil_rate                 0.0
dtype: float64
prod_hrs                 1.0
bhp                      1.0
bht                      1.0
dp_tubing                1.0
AVG_ANNULUS_PRESS        1.0
AVG_CHOKE_SIZE_P         1.0
whp                      1.0
wht                      1.0
choke_size_percentage    1.0
oil_vol                  1.0
gas_vol                  1.0
water_vol                1.0
linear_regressor         1.0
EMA_short                1.0
EMA_medium               1.0
EMA_long                 1.0
Rolling_short            1.0
Rolling_medium           1.0
Rolling_long             1.0
oil_rate                 1.0
dtype: float64

In [29]:
data.to_pickle(path + "/data/Volve/Volve_cleaned_prepared.pkl")

In [30]:
data = pd.read_pickle(path + r'/data/Volve/Volve_cleaned_prepared.pkl')
data.head()

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,...,linear_regressor,EMA_short,EMA_medium,EMA_long,Rolling_short,Rolling_medium,Rolling_long,Lag_short,Lag_medium,Lag_long
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029311,0.605973,0.396167,-2.016027,-0.533280,3.281836,...,-0.101892,-0.103579,-0.104768,-0.106929,-0.001355,-0.002618,-0.00519,"[0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845795,0.634777,0.239818,0.088113,-0.419656,2.849981,...,-0.101892,-0.103579,-0.104768,-0.106929,-0.001355,-0.002618,-0.00519,"[0.0, 0.0, -0.10230979661544379]","[0.0, 0.0, 0.0, 0.0, -0.10230979661544379]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775025,0.639809,0.199890,-0.688434,-0.402874,2.607708,...,-0.101892,-0.009618,-0.053295,-0.079801,-0.001355,-0.002618,-0.00519,"[0.0, -0.10230979661544379, -0.10230979661544379]","[0.0, 0.0, 0.0, -0.10230979661544379, -0.10230...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.10..."
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705033,0.642084,0.161493,1.145283,-0.379061,2.364038,...,-0.114759,-0.020781,-0.051611,-0.076565,-0.001355,-0.002618,-0.00519,"[-0.10230979661544379, -0.10230979661544379, 0...","[0.0, 0.0, -0.10230979661544379, -0.1023097966...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.1023097..."
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625357,0.643889,0.117221,1.145283,-0.340115,2.088747,...,0.082297,-0.004428,-0.037199,-0.066767,-0.009496,-0.002618,-0.00519,"[-0.10230979661544379, 0.1777063666263608, -0....","[0.0, -0.10230979661544379, -0.102309796615443...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.102309796615..."

In [31]:
data_expanded = data.copy()
for column in ['Lag_short', 'Lag_medium', 'Lag_long']:
    # Expand the 'lists' column into separate columns
    expanded_lists = pd.DataFrame(data[column].tolist(), columns=[column+f"_{i}" for i in range(len(data.loc[0, column]))], index=data.index)
    # Join the expanded columns back to the original DataFrame
    data_expanded = data_expanded.join(expanded_lists)
    # Optionally, drop the original list columns
    data_expanded.drop(columns=column, inplace=True)

data_expanded

,well_name,WELL_BORE_CODE,date,prod_hrs,bhp,bht,dp_tubing,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,whp,...,Lag_long_0,Lag_long_1,Lag_long_2,Lag_long_3,Lag_long_4,Lag_long_5,Lag_long_6,Lag_long_7,Lag_long_8,Lag_long_9
0,7405,NO 15/9-F-1 C,2014-04-22,0.268405,1.029311,0.605973,0.396167,-2.016027,-0.533280,3.281836,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,7405,NO 15/9-F-1 C,2014-04-23,0.268405,0.845795,0.634777,0.239818,0.088113,-0.419656,2.849981,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.102310
2,7405,NO 15/9-F-1 C,2014-04-24,0.268405,0.775025,0.639809,0.199890,-0.688434,-0.402874,2.607708,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.102310,-0.102310
3,7405,NO 15/9-F-1 C,2014-04-25,0.268405,0.705033,0.642084,0.161493,1.145283,-0.379061,2.364038,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.102310,-0.102310,0.177706
4,7405,NO 15/9-F-1 C,2014-04-26,0.268405,0.625357,0.643889,0.117221,1.145283,-0.340115,2.088747,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.102310,-0.102310,0.177706,-0.042238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7982,5769,NO 15/9-F-5 AH,2016-08-22,0.268405,-0.880933,-0.806036,-0.814175,1.149266,1.150153,-1.140330,...,-0.713393,-0.712867,-0.704496,-0.697462,-0.690866,-0.693342,-0.687878,-0.685242,-0.694343,-0.684087
7983,5769,NO 15/9-F-5 AH,2016-08-23,0.268405,-0.880933,-0.806036,-0.814175,1.158798,1.150153,-1.136215,...,-0.712867,-0.704496,-0.697462,-0.690866,-0.693342,-0.687878,-0.685242,-0.694343,-0.684087,-0.683109
7984,5769,NO 15/9-F-5 AH,2016-08-24,0.268405,-0.880933,-0.806036,-0.814175,1.141085,1.150153,-1.137527,...,-0.704496,-0.697462,-0.690866,-0.693342,-0.687878,-0.685242,-0.694343,-0.684087,-0.683109,-0.677835
7985,5769,NO 15/9-F-5 AH,2016-08-25,0.268405,-1.334973,-1.285316,-1.327391,1.140689,1.150153,-1.140776,...,-0.697462,-0.690866,-0.693342,-0.687878,-0.685242,-0.694343,-0.684087,-0.683109,-0.677835,-0.679069
7986,5769,NO 15/9-F-5 AH,2016-08-26,-0.744073,-0.434704,-0.323038,-0.323127,1.127728,0.671086,-1.123420,...,-0.690866,-0.693342,-0.687878,-0.685242,-0.694343,-0.684087,-0.683109,-0.677835,-0.679069,-0.678646

In [32]:
data_expanded.to_pickle(path + "/data/Volve/Volve_cleaned_prepared_flattened.pkl")

In [40]:
train_size = 0.6
val_size = 0.2
test_size = 0.2

In [41]:
train_wells = []
test_wells = []
for i in well_info.keys():
    well = data_expanded[data_expanded['well_name'] == i]
    train_set_length = int((train_size + val_size) * len(well))
    print(train_set_length)
    train_wells.append(well[:train_set_length + 1])
    test_set_length = int(test_size * len(well))
    test_wells.append(well[-test_set_length:])

# Flatten the lists of DataFrames
temp_data = pd.concat(train_wells).reset_index(drop=True)
data_test = pd.concat(test_wells).reset_index(drop=True)

data_test.reset_index(drop=True, inplace=True)

data_test.to_pickle(path + "/data/Volve/data_test_flattened.pkl")